CREATE TABLE IF NOT EXISTS patch_cache (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  version TEXT NOT NULL,
  language TEXT NOT NULL DEFAULT 'en_US',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  level TEXT NOT NULL,
  event TEXT NOT NULL,
  message TEXT,
  metadata TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);